#!/usr/bin/env python
import argparse
import os
import glob
import pandas as pd

PARSER = argparse.ArgumentParser(description="Short script to combine the dataframes generated by all the simulations"
                                             "that are part of the same set.")

PARSER.add_argument("--path_set",
                    metavar="STRING", dest="path_set", default='', type=str,
                    help="Path to the 'set' folder where the simulations of a given set have all been saved.")

ARGS = PARSER.parse_args()

path_set = ARGS.path_set

os.chdir(path_set)

folders = os.listdir()

# Defining two dataframes
dist_comps_all = pd.DataFrame(columns=['Model', 'Mut_sigma', 'Mut_ratio', 'Mut_alpha', 'Mut_corr', 'Iter',
                                       'Folder', 'Set', 'Comparison', 'Property', 'Type', 'Moods_stat', 'Moods_p-val',
                                       'KS_stat', 'KS_p-val'])

dist_corrs_all = pd.DataFrame(columns=['Model', 'Mut_sigma', 'Mut_ratio', 'Mut_alpha', 'Mut_corr', 'Iter',
                                       'Folder', 'Set', 'Type', 'rho_fold', 'p-val_fold', 'rho_signed',
                                       'p-val_signed', 'rho_ratio', 'p-val_ratio'])

for folder in folders:

    if os.path.isdir(folder):
        os.chdir(folder)
        df_comps = pd.concat(map(pd.read_csv, glob.glob('distribution_comps*.csv')))
        df_corrs = pd.concat(map(pd.read_csv, glob.glob('Correlations*.csv')))

        dist_comps_all = pd.concat([dist_comps_all, df_comps]).reset_index(drop=True)
        dist_corrs_all = pd.concat([dist_corrs_all, df_corrs]).reset_index(drop=True)

        os.chdir(os.path.dirname(os.getcwd()))

# Mood's and KS Stats for each individual property
dist_stats_all = dist_comps_all[['Model', 'Mut_sigma', 'Mut_ratio', 'Mut_alpha', 'Mut_corr', 'Iter',
                                 'Folder', 'Set', 'Comparison', 'Property', 'Type', 'Moods_stat', 'Moods_p-val',
                                 'KS_stat', 'KS_p-val']].copy()

# Mood's and KS means across all properties
dist_stats_means = dist_comps_all[['Model', 'Mut_sigma', 'Mut_ratio', 'Mut_alpha', 'Mut_corr', 'Iter',
                                   'Folder', 'Set', 'Comparison', 'Type', 'Moods_stat', 'Moods_p-val',
                                   'KS_stat', 'KS_p-val']].copy()
dist_stats_means = dist_stats_means.groupby(by=['Model', 'Mut_sigma', 'Mut_ratio', 'Mut_alpha', 'Mut_corr', 'Iter',
                                                'Folder', 'Set', 'Comparison', 'Type'], as_index=False).mean()
dist_stats_means = dist_stats_means.reset_index(drop=True)

# Saving the three dataframes
set_name = dist_stats_all.at[0, 'Set']
dist_stats_all.to_csv(os.path.join(f'Dist_stats_all_{set_name}.csv'), index=False)
dist_stats_means.to_csv(os.path.join(f'Dist_stats_means_{set_name}.csv'), index=False)
dist_corrs_all.to_csv(os.path.join(f'Correlations_all_{set_name}.csv'), index=False)
